### ISSUE TITLE
electron5.0.3 ia32 error Uncaught TypeError: edge.initializeClrFunc is not a function

### ISSUE THREAD

**Issue by wave314** [agracio/electron-edge-js#54]
Hi,
I have a problem,   
**development environment**： nodejs 12.8.0 (x64) , electron 5.0.3(**x64**) , electron-edge-js 12.0.1
the demo is ok, but when i update electron to 5.0.3(**x86**) and rebuild .net dll to x86 then delete node_modules folder then run npm i
command, the demo is failed, it output error "Uncaught TypeError: edge.initializeClrFunc is not a function", the main code is [
process.env.EDGE_USE_CORECLR = 1;
var edge = require("electron-edge-js");

var helloWorld = edge.func(function() {
/*
async (input) => {
return ".NET Welcomes " + input.ToString();
}
*/
});

helloWorld("JavaScript", function(error, result) {
if (error) throw error;
alert("hello");
});]
demo is https://github.com/agracio/electron-edge-js-quick-start

**Comment by Hammster** [comment]
Please enable `nodeIntegration` in your `webPreferences` for the window

**Comment by wave314** [comment]
> Please enable `nodeIntegration` in your `webPreferences` for the window

Yes, I did, but it was the same error

**Comment by XRenSiu** [comment]
electron: 5.0.3

platform: win32

I have the same error.

`Uncaught TypeError: edge.initializeClrFunc is not a function`
@agracio @wave314

**Comment by wave314** [comment]
I still have this error

**Comment by wave314** [comment]
> electron: 5.0.3
> 
> electron-edge-js: 12.0.1
> 
> platform: win32
> 
> I have the same error.
> 
> `Uncaught TypeError: edge.initializeClrFunc is not a function`
> @agracio @wave314
I still have the error

**Comment by XRenSiu** [comment]
@agracio could you fix it soon?

**Comment by agracio** [comment]
New version with fix for .NET Native and support for Electron 6.0.x released to NPM.
