### ISSUE TITLE
electron5.0.3 error Uncaught TypeError: edge.initializeClrFunc is not a function

### ISSUE THREAD

**Issue by wave314** [agracio/electron-edge-js#52]
**envirenment： nodejs 12.0.0 (x86) , electron 4.0.4 , electron-edge-js 12.0.1**
the demo is ok, but **when i update electron to 5.0.3 and delete node_modules folder then run npm i   
command, the demo is failed**, it output error "Uncaught TypeError: edge.initializeClrFunc is not a function", the main code is [
process.env.EDGE_USE_CORECLR = 1;
var edge = require("electron-edge-js");

var helloWorld = edge.func(function() {
  /*
  async (input) => {
      return ".NET Welcomes " + input.ToString();
  }
*/
});

helloWorld("JavaScript", function(error, result) {
  if (error) throw error;
  alert("hello");
});]
when i use nodejs **12.0.0(x64)** the demo is ok.  I run "build.bat release 12.0.0" command in electron-edge-js folder rebuild is success, but the error is save
**demo is https://github.com/agracio/electron-edge-js-quick-start**

Does anyone have any Suggestions

**Comment by wave314** [comment]
when i use nodejs 12.0.0(x64) the demo is ok.  I run "build.bat release 12.0.0" command in electron-edge-js folder rebuild is success, but the error is save
