### ISSUE TITLE
Uncaught Error with "edge_nativeclr.node"

### ISSUE THREAD

**Issue by payot-inc** [agracio/electron-edge-js#42]
![image](https://user-images.githubusercontent.com/43327756/55524754-5ec69a80-56c9-11e9-9a48-7b50b963c811.png)

Hi, I have an project and it works well with the 'electron-edge-js' 10.11.0.
We duplicated it to new project for upgrading and it uses 10.11.1.

but whatever I do, it shows this error.

How can i solve it?

**Comment by mbsg** [comment]
I have the same problem
`Error: Cannot find module 'project_root\dist_electron\native\win32\x64\12.4.0\edge_nativeclr'`
Electron v6.1.0
Node v12.4.0
vue/cli 4.0.4
windows 10 1903 x64
